language: php
php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - composer global require "hirak/prestissimo:^0.3"
install:
  - composer install --no-interaction
script:
  # Inspections
  - ./vendor/bin/phpcs src
  - ./vendor/bin/phpstan analyze src
  - ./vendor/bin/phpunit

  # Try to add to a Drupal setup.
  - composer create-project drupal-composer/drupal-project:8.x-dev $TRAVIS_BUILD_DIR/../drupal --no-interaction
  - cd $TRAVIS_BUILD_DIR/../drupal

  # Install dependency.
  - composer config repositories.0 path $TRAVIS_BUILD_DIR
  - cat composer.json
  - composer require mglaman/phpstan-drupal *@dev
  - cp $TRAVIS_BUILD_DIR/tests/fixtures/drupal-phpstan.neon phpstan.neon
  - ./vendor/bin/phpstan analyze web/core/install.php
  - ./vendor/bin/phpstan analyze web/core/modules/migrate_drupal --no-progress | grep -q "tests/fixtures" && echo 1 || echo 0

cache:
  directories:
    - $HOME/.composer/cache
