name: "Deploy Website"
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-website.yml'
      - 'website/**'
concurrency: app_build
jobs:
  build:
    name: "Build & deploy"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: "20
      - name: "npm install"
        working-directory: ./website
        run: "npm install"
      - name: "npm build"
        working-directory: ./website
        run: "npm run build"
      - name: "configure AWS"
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy
        working-directory: ./app
        run: aws s3 sync ./dist s3://phpstan-drupal-web
      - name: Invalidate CloudFront
        working-directory: ./app
        run: aws cloudfront create-invalidation --distribution-id EJLWUQZMNXH6E --paths "/*"
